//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CROUDClientesConsumidorServidorWeb.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CROUDClientesServiceSoap", Namespace="http://tempuri.org/")]
    public partial class CROUDClientesService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback MostrarClientesOperationCompleted;
        
        private System.Threading.SendOrPostCallback AztualizarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback FiltrarClientesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CROUDClientesService() {
            this.Url = global::CROUDClientesConsumidorServidorWeb.Properties.Settings.Default.CROUDClientesConsumidorServidorWeb_localhost_CROUDClientesService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event InsertarClienteCompletedEventHandler InsertarClienteCompleted;
        
        /// <remarks/>
        public event EliminarClienteCompletedEventHandler EliminarClienteCompleted;
        
        /// <remarks/>
        public event MostrarClientesCompletedEventHandler MostrarClientesCompleted;
        
        /// <remarks/>
        public event AztualizarUsuarioCompletedEventHandler AztualizarUsuarioCompleted;
        
        /// <remarks/>
        public event FiltrarClientesCompletedEventHandler FiltrarClientesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int InsertarCliente(string nombre, string primerApellido, string segundoApellido) {
            object[] results = this.Invoke("InsertarCliente", new object[] {
                        nombre,
                        primerApellido,
                        segundoApellido});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void InsertarClienteAsync(string nombre, string primerApellido, string segundoApellido) {
            this.InsertarClienteAsync(nombre, primerApellido, segundoApellido, null);
        }
        
        /// <remarks/>
        public void InsertarClienteAsync(string nombre, string primerApellido, string segundoApellido, object userState) {
            if ((this.InsertarClienteOperationCompleted == null)) {
                this.InsertarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertarClienteOperationCompleted);
            }
            this.InvokeAsync("InsertarCliente", new object[] {
                        nombre,
                        primerApellido,
                        segundoApellido}, this.InsertarClienteOperationCompleted, userState);
        }
        
        private void OnInsertarClienteOperationCompleted(object arg) {
            if ((this.InsertarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertarClienteCompleted(this, new InsertarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EliminarCliente(int id) {
            object[] results = this.Invoke("EliminarCliente", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarClienteAsync(int id) {
            this.EliminarClienteAsync(id, null);
        }
        
        /// <remarks/>
        public void EliminarClienteAsync(int id, object userState) {
            if ((this.EliminarClienteOperationCompleted == null)) {
                this.EliminarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarClienteOperationCompleted);
            }
            this.InvokeAsync("EliminarCliente", new object[] {
                        id}, this.EliminarClienteOperationCompleted, userState);
        }
        
        private void OnEliminarClienteOperationCompleted(object arg) {
            if ((this.EliminarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarClienteCompleted(this, new EliminarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MostrarClientes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable MostrarClientes() {
            object[] results = this.Invoke("MostrarClientes", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void MostrarClientesAsync() {
            this.MostrarClientesAsync(null);
        }
        
        /// <remarks/>
        public void MostrarClientesAsync(object userState) {
            if ((this.MostrarClientesOperationCompleted == null)) {
                this.MostrarClientesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMostrarClientesOperationCompleted);
            }
            this.InvokeAsync("MostrarClientes", new object[0], this.MostrarClientesOperationCompleted, userState);
        }
        
        private void OnMostrarClientesOperationCompleted(object arg) {
            if ((this.MostrarClientesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MostrarClientesCompleted(this, new MostrarClientesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AztualizarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable AztualizarUsuario(string id, string nombre, string primerApellido, string segundoApellido, System.DateTime fechaAfiliacion) {
            object[] results = this.Invoke("AztualizarUsuario", new object[] {
                        id,
                        nombre,
                        primerApellido,
                        segundoApellido,
                        fechaAfiliacion});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void AztualizarUsuarioAsync(string id, string nombre, string primerApellido, string segundoApellido, System.DateTime fechaAfiliacion) {
            this.AztualizarUsuarioAsync(id, nombre, primerApellido, segundoApellido, fechaAfiliacion, null);
        }
        
        /// <remarks/>
        public void AztualizarUsuarioAsync(string id, string nombre, string primerApellido, string segundoApellido, System.DateTime fechaAfiliacion, object userState) {
            if ((this.AztualizarUsuarioOperationCompleted == null)) {
                this.AztualizarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAztualizarUsuarioOperationCompleted);
            }
            this.InvokeAsync("AztualizarUsuario", new object[] {
                        id,
                        nombre,
                        primerApellido,
                        segundoApellido,
                        fechaAfiliacion}, this.AztualizarUsuarioOperationCompleted, userState);
        }
        
        private void OnAztualizarUsuarioOperationCompleted(object arg) {
            if ((this.AztualizarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AztualizarUsuarioCompleted(this, new AztualizarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FiltrarClientes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable FiltrarClientes(string nombre, System.DateTime fechaInicio, System.DateTime fechaFinal) {
            object[] results = this.Invoke("FiltrarClientes", new object[] {
                        nombre,
                        fechaInicio,
                        fechaFinal});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void FiltrarClientesAsync(string nombre, System.DateTime fechaInicio, System.DateTime fechaFinal) {
            this.FiltrarClientesAsync(nombre, fechaInicio, fechaFinal, null);
        }
        
        /// <remarks/>
        public void FiltrarClientesAsync(string nombre, System.DateTime fechaInicio, System.DateTime fechaFinal, object userState) {
            if ((this.FiltrarClientesOperationCompleted == null)) {
                this.FiltrarClientesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFiltrarClientesOperationCompleted);
            }
            this.InvokeAsync("FiltrarClientes", new object[] {
                        nombre,
                        fechaInicio,
                        fechaFinal}, this.FiltrarClientesOperationCompleted, userState);
        }
        
        private void OnFiltrarClientesOperationCompleted(object arg) {
            if ((this.FiltrarClientesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FiltrarClientesCompleted(this, new FiltrarClientesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void InsertarClienteCompletedEventHandler(object sender, InsertarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void EliminarClienteCompletedEventHandler(object sender, EliminarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void MostrarClientesCompletedEventHandler(object sender, MostrarClientesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MostrarClientesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MostrarClientesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AztualizarUsuarioCompletedEventHandler(object sender, AztualizarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AztualizarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AztualizarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void FiltrarClientesCompletedEventHandler(object sender, FiltrarClientesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FiltrarClientesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FiltrarClientesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591